### ISSUE TITLE
Hide controls on fullScreen mode

### ISSUE THREAD

**Issue by zzarcon** [zzarcon/react-video-renderer#2]
Should this component take of hiding the native controls when `controls={false}` on full screen mode?

```css
video::-webkit-media-controls {
  display:none !important;
}
```
